# 1. Find the 10 countries with most projects

## Import & Inspect Data

In [1]:
import pandas as pd
import json
from pandas.io.json import json_normalize

json_data_df = pd.read_json('data/world_bank_projects.json')
print(json_data_df.columns)
json_data_df.head()

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

## Count country names

In [2]:
# Check to see if there are only strings in each entry of 'project_name', indicating that there are no nested lists/dictionaries.
# This means that every entry in our DataFrame contains only one project.
count = 0
for idx, entry in enumerate(json_data_df['project_name']):
    if type(entry) != str:
        print('Entry ' + str(idx) + 'is not a string')
        count += 1

if count == 0:
    print("All entries in the 'project_name' column are strings.")

All entries in the 'project_name' column are strings.

In [3]:
# Since each entry in project_name is a string, then we can just count the number of times each country is mentioned and 
# list the top 10.
json_data_df['countryshortname'].value_counts().iloc[0:10]

Indonesia             19
China                 19
Vietnam               17
India                 16
Yemen, Republic of    13
Morocco               12
Bangladesh            12
Nepal                 12
Mozambique            11
Africa                11
Name: countryshortname, dtype: int64

# 2. Top 10 Major Project Themes

## Open and reorder data

In [4]:
# Re-open json data as a list and normalize it
with open('data/world_bank_projects.json') as json_file:
    json_data_list = json.load(json_file)
json_data_norm = json_normalize(json_data_list, 'mjtheme_namecode', ['countryshortname', 'project_name'])
json_data_norm.columns = ['theme_code', 'theme_name', 'country', 'project_name']
json_data_norm.head()

,theme_code,theme_name,country,project_name
0,8,Human development,Ethiopia,Ethiopia General Education Quality Improvement...
1,11,,Ethiopia,Ethiopia General Education Quality Improvement...
2,1,Economic management,Tunisia,TN: DTF Social Protection Reforms Support
3,6,Social protection and risk management,Tunisia,TN: DTF Social Protection Reforms Support
4,5,Trade and integration,Tuvalu,Tuvalu Aviation Investment Project - Additiona...

In [5]:
# Change theme_code column to type int
json_data_norm['theme_code'] = pd.to_numeric(json_data_norm['theme_code'])
json_data_norm.dtypes

theme_code       int64
theme_name      object
country         object
project_name    object
dtype: object

In [6]:
# Re-arrange the columns
cols_rearrange = ['country',  'project_name', 'theme_code', 'theme_name']
json_data_norm = json_data_norm[cols_rearrange]
json_data_norm.head()

,country,project_name,theme_code,theme_name
0,Ethiopia,Ethiopia General Education Quality Improvement...,8,Human development
1,Ethiopia,Ethiopia General Education Quality Improvement...,11,
2,Tunisia,TN: DTF Social Protection Reforms Support,1,Economic management
3,Tunisia,TN: DTF Social Protection Reforms Support,6,Social protection and risk management
4,Tuvalu,Tuvalu Aviation Investment Project - Additiona...,5,Trade and integration

## Count and show the top 10 major project themes
Count the instances of the project and store in a proj_themes_top dataframe, create a dictionary where the key is the theme_code and the value is the theme_name, and then use the dictionary to create a new column in proj_themes_top with a map of our dictionary

In [7]:
# Count the theme_code values, since theme_name has missing values
proj_themes_top = json_data_norm['theme_code'].value_counts().iloc[0:10]
proj_themes_top = pd.DataFrame(proj_themes_top)  # turn Series into DataFrame
proj_themes_top = proj_themes_top.reset_index()  # reset the index
proj_themes_top.columns = ['theme_code', 'num_instances']  # rename the columns
proj_themes_top

   theme_code  num_instances
0          11            250
1          10            216
2           8            210
3           2            199
4           6            168
5           4            146
6           7            130
7           5             77
8           9             50
9           1             38

In [8]:
# Create a dictionary where the key is the theme_code and the value is the theme_name
theme_dict = {}
for code, name in json_data_norm[['theme_code', 'theme_name']].itertuples(index=False):
    if (name != '') & (not(int(code) in theme_dict)):  # only if name isn't emtpy and code isn't in theme_dict
        theme_dict[int(code)] = name  # convert key to int

# sort the dictionary
theme_dict = dict(sorted(theme_dict.items()))
theme_dict

{1: 'Economic management',
 2: 'Public sector governance',
 3: 'Rule of law',
 4: 'Financial and private sector development',
 5: 'Trade and integration',
 6: 'Social protection and risk management',
 7: 'Social dev/gender/inclusion',
 8: 'Human development',
 9: 'Urban development',
 10: 'Rural development',
 11: 'Environment and natural resources management'}

In [9]:
# Map a new column into proj_themes_top with our dictionary
proj_themes_top['theme_name'] = proj_themes_top['theme_code'].map(theme_dict)
proj_themes_top = proj_themes_top[['theme_code', 'theme_name', 'num_instances']]  # rearranged the columns
proj_themes_top

   theme_code                                    theme_name  num_instances
0          11  Environment and natural resources management            250
1          10                             Rural development            216
2           8                             Human development            210
3           2                      Public sector governance            199
4           6         Social protection and risk management            168
5           4      Financial and private sector development            146
6           7                   Social dev/gender/inclusion            130
7           5                         Trade and integration             77
8           9                             Urban development             50
9           1                           Economic management             38

# 3. Create a DataFrame with missing theme names filled in
We'll just use the theme_dict dictionary we created in 2. and map the 'theme_name' column of json_data_norm with a filter only on empty instances

In [10]:
for idx, code, name in json_data_norm[['theme_code', 'theme_name']].itertuples(index=True):
    if name == '':
        json_data_norm.iloc[idx, -1] = theme_dict[code]
        
json_data_norm

,country,project_name,theme_code,theme_name
0,Ethiopia,Ethiopia General Education Quality Improvement...,8,Human development
1,Ethiopia,Ethiopia General Education Quality Improvement...,11,Environment and natural resources management
2,Tunisia,TN: DTF Social Protection Reforms Support,1,Economic management
3,Tunisia,TN: DTF Social Protection Reforms Support,6,Social protection and risk management
4,Tuvalu,Tuvalu Aviation Investment Project - Additiona...,5,Trade and integration
5,Tuvalu,Tuvalu Aviation Investment Project - Additiona...,2,Public sector governance
6,Tuvalu,Tuvalu Aviation Investment Project - Additiona...,11,Environment and natural resources management
7,Tuvalu,Tuvalu Aviation Investment Project - Additiona...,6,Social protection and risk management
8,"Yemen, Republic of",Gov't and Civil Society Organization Partnership,7,Social dev/gender/inclusion
9,"Yemen, Republic of",Gov't and Civil Society Organization Partnership,7,Social dev/gender/inclusion
10,Lesotho,Second Private Sector Competitiveness and Econ...,5,Trade and integration
11,Lesotho,Second Private Sector Competitiveness and Econ...,4,Financial and private sector development
12,Kenya,Additional Financing for Cash Transfers for Or...,6,Social protection and risk management
13,Kenya,Additional Financing for Cash Transfers for Or...,6,Social protection and risk management
14,India,National Highways Interconnectivity Improvemen...,2,Public sector governance
15,India,National Highways Interconnectivity Improvemen...,4,Financial and private sector development
16,China,China Renewable Energy Scale-Up Program Phase II,11,Environment and natural resources management
17,China,China Renewable Energy Scale-Up Program Phase II,8,Human development
18,India,Rajasthan Road Sector Modernization Project,10,Rural development
19,India,Rajasthan Road Sector Modernization Project,7,Social dev/gender/inclusion
20,Morocco,MA Accountability and Transparency DPL,2,Public sector governance
21,Morocco,MA Accountability and Transparency DPL,2,Public sector governance
22,Morocco,MA Accountability and Transparency DPL,2,Public sector governance
23,South Sudan,Southern Sudan Emergency Food Crisis Response ...,10,Rural development
24,South Sudan,Southern Sudan Emergency Food Crisis Response ...,2,Public sector governance
25,India,Uttarakhand Disaster Recovery Project,10,Rural development
26,India,Uttarakhand Disaster Recovery Project,6,Social protection and risk management
27,India,Uttarakhand Disaster Recovery Project,6,Social protection and risk management
28,India,Uttarakhand Disaster Recovery Project,11,Environment and natural resources management
29,Ghana,GH eTransform Ghana,4,Financial and private sector development
...,...,...,...,...
1469,Brazil,RIO STATE DEVELOPMENT POLICY LOAN III,8,Human development
1470,Papua New Guinea,Papua New Guinea Settlement Upgrading Programme,9,Urban development
1471,Papua New Guinea,Papua New Guinea Settlement Upgrading Programme,6,Social protection and risk management
1472,Papua New Guinea,Papua New Guinea Settlement Upgrading Programme,6,Social protection and risk management
1473,Papua New Guinea,Papua New Guinea Settlement Upgrading Programme,9,Urban development
1474,Nepal,Nepal PFM-MDTF Strengthening Civil Society Org...,2,Public sector governance
1475,Nepal,Nepal PFM-MDTF Strengthening Civil Society Org...,2,Public sector governance
1476,West Bank and Gaza,Water Supply and Sanitation Improvements for W...,10,Rural development
1477,West Bank and Gaza,Water Supply and Sanitation Improvements for W...,11,Environment and natural resources management
1478,Pakistan,Pakistan: Promoting Girls' Education in Baloch...,8,Human development
1479,Pakistan,Pakistan: Promoting Girls' Education in Baloch...,7,Social dev/gender/inclusion
1480,Bangladesh,Revision and Alignment of NAP with UNCCD 10-ye...,11,Environment and natural resources management
1481,Bangladesh,Revision and Alignment of NAP with UNCCD 10-ye...,5,Trade and integration
1482,Nepal,Nepal: Pilot Project for Seismic School Safety...,6,Social protection and risk management
1483,Nepal,Nepal: Pilot Project for Seismic School Safety...,8,Human development
1484,Jamaica,Technological Scale Up for Youth-led Urban Orn...,4,Financial and private sector development
1485,Jamaica,Technological Scale Up for Youth-led Urban Orn...,7,Social dev/gender/inclusion
1486,Lao People's Democratic Republic,Lao Eight Poverty Reduction Support,8,Human development
1487,Lao People's Democratic Republic,Lao Eight Poverty Reduction Support,5,Trade and integration
1488,Lao People's Democratic Republic,Lao Eight Poverty Reduction Support,2,Public sector governance
1489,Lao People's Democratic Republic,Lao Eight Poverty Reduction Support,8,Human development
1490,Guinea,Second Emergency Agricultural Productivity Sup...,10,Rural development
1491,Guinea,Second Emergency Agricultural Productivity Sup...,6,Social protection and risk management
1492,Indonesia,Sustainable Management of Agricultural Researc...,10,Rural development
1493,Indonesia,Sustainable Management of Agricultural Researc...,10,Rural development
1494,Indonesia,Sustainable Management of Agricultural Researc...,10,Rural development
1495,Kenya,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,9,Urban development
1496,Kenya,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,8,Human development
1497,Kenya,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,5,Trade and integration
1498,Kenya,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,4,Financial and private sector development